app/urls.py
from django.urls import path
from app import views

urlpatterns = [
    # 一覧表示
    path('', views.UserIndexView.as_view(), name='index'),
    # 詳細表示
    path('detail/<int:pk>/', views.UserDetailView.as_view(), name='detail'),
    # 新規登録
    path('create', views.UserCreateView.as_view(), name='create'),
    # int型のプライマリーキーとなる、つまり「update/1/」や「update/2/」など
    # 更新・編集
    path('update/<int:pk>/', views.UserUpdateView.as_view(), name='update'),
    # 削除
    path('delete/<int:pk>/', views.UserDeleteView.as_view(), name='delete'),
    
    # 利用記録
    # 一覧表示
    path('ur_use_list/', views.UR_UseListView.as_view(), name='ur_use_list'),
    # 登録
    path('ur_create/', views.UR_CreateView.as_view(), name='ur_create'),
    # 更新・編集
    path('ur_update/<int:pk>/', views.UR_UpdateView.as_view(), name='ur_update'),
    # 削除
    path('delete/<int:pk>/', views.UR_DeleteView.as_view(), name='ur_delete'),

]

cm_system/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path("admin/", admin.site.urls),
    
    path("login/", LoginView.as_view(), name='login'),
    path("logout/", LogoutView.as_view(), name='logout'),
    #path('accounts/', include('django.contrib.auth.urls')),
    path('', include('app.urls')),
]

app/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator

# Create your models here.
# 利用者概要のモデル
class UserOverview(models.Model):
    # 性別選択リスト
    GENDER_CHOICES = (
        (1, '男性'),
        (2, '女性'),
        (3, 'その他'),
    )
    
    # 主キー カード番号
    id = models.AutoField(
        verbose_name = 'カード番号',
        primary_key = True,
    )

    # 名前
    name = models.CharField(
        verbose_name = '氏名',
        max_length = 200,  
    )
    
    # 生年月日
    birthday = models.DateField(
        verbose_name = '生年月日',
    )
    
    # 性別
    gender = models.IntegerField(
        verbose_name = '性別',
        choices = GENDER_CHOICES,
        default = 1,
    )
    
    # 郵便番号1
    zip_code1 = models.CharField(
        verbose_name = '郵便番号1',
        max_length = 3,
    )
    # 郵便番号2
    zip_code2 = models.CharField(
        verbose_name = '郵便番号2',
        max_length = 4,
    )

    # 住所
    address = models.CharField(
        verbose_name = '住所',
        max_length = 200,
    )
    
    # 電話番号
    phone_number = models.CharField(
        verbose_name = '電話番号',
        max_length = 20,
    )
    
    # 体温
    temperature = models.DecimalField(
        verbose_name = '体温',
        max_digits = 3,
        decimal_places = 1,
    )
    
    # 作成日
    created_date = models.DateField(
        verbose_name = '作成日',
        auto_now_add = True,
    )
    
    # 以下は管理サイト上の表示設定
    def __str__(self):
        return str(self.id)

    class Meta:
        # verbose_name = '利用者概要'
        # ↑ 下記が明記されている場合は上記は要らず
        # ↓ 複数形のsを付けないために必要
        verbose_name_plural = '利用者概要'
        

# 利用記録のモデル
class UsageRecord(models.Model): 
    # 利用日
    use_date = models.DateField(
        verbose_name = '利用日',
        auto_now_add = True,
    )
    
    # 利用時間帯リスト
    SESSION_CHOICES = (
        (1, '午前の部'),
        (2, '午後の部'),
        (3, '夜の部'),
    )
    
    # 利用時間帯(何の部か)
    use_session = models.IntegerField(
        verbose_name = '利用時間帯',
        choices = SESSION_CHOICES,
        default = 1,
    )
    
    # 外部キー 利用者概要 カード番号
    useroverview_fk = models.ForeignKey(
        UserOverview, 
        on_delete = models.CASCADE,
        to_field = 'id',
    )
        
    # 以下は管理サイト上の表示設定
    def __str__(self):
        # 文字列にしないとエラーを起こす為
        return str(self.use_date)

    class Meta:
        # ↑ 下記が明記されている場合は上記は要らず
        # ↓ 複数形のsを付けないために必要
        verbose_name_plural = '利用記録'

app/forms.py
from django.forms import ModelForm
from app.models import UserOverview, UsageRecord

class UserOverviewForm(ModelForm):
    class Meta:
        # modelの指定
        model = UserOverview
        # 入力をする項目を指定
        fields = ("name", "birthday", "gender", "zip_code1", "zip_code2", "address", "phone_number", "temperature",)
   
class UsageRecordForm(ModelForm):
    class Meta:
        model = UsageRecord
        fields = ("useroverview_fk","use_session",)

app/views.py
from re import U
from django.shortcuts import render
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
#from requests import session
from app.models import UserOverview, UsageRecord
from app.forms import UserOverviewForm, UsageRecordForm
from django.urls import reverse_lazy

# 一覧表示ビュー
# 検索機能あり
class UserIndexView(ListView):
    # 表示するhtmlの指定
    template_name = "app/useroverview/index.html"
    # modelの指定
    model = UserOverview
    # オブジェクト名をuseroverviewsに指定
    # htmlにて情報を指定する場合に使用
    # 定義しなかった場合、デフォルトで
    # 'モデルクラス名' (小文字) が設定されることになる
    context_object_name = "useroverviews"
    # ページング機能
    paginate_by = 10
    
    # 検索機能追加の為
    # viewが表示するオブジェクトのクエリセットを
    # 返すために使用
    def get_queryset(self):
        serch_name = self.request.GET.get('query')
        
        if serch_name:
            # 部分一致
            name_list = UserOverview.objects.order_by('-id').filter(name__icontains = serch_name)
            # 降順に整列
            #name_list = UserOverview.objects.order_by('-id')

        else:
            # 全てを表示
            name_list = UserOverview.objects.all()
            # 降順に整列
            name_list = UserOverview.objects.order_by('-id')

        return name_list

# 詳細表示ビュー
class UserDetailView(DetailView):
    template_name = "app/useroverview/detail.html"
    model = UserOverview
    context_object_name = "userdetailviews"

# 作成ビュー
class UserCreateView(CreateView):
    template_name = "app/useroverview/create.html"
    model = UserOverview
    # form_classの指定 (forms.pyでクラス定義)
    form_class = UserOverviewForm
    # 登録成功時に遷移する
    success_url = reverse_lazy("index")
    
# 更新・編集ビュー
class UserUpdateView(UpdateView):
    template_name = "app/useroverview/update.html"
    model = UserOverview
    form_class = UserOverviewForm
    success_url = reverse_lazy("index")
    
# 削除ビュー
class UserDeleteView(DeleteView):
    template_name = "app/useroverview/index.html"
    model = UserOverview
    success_url = reverse_lazy("index")


# 利用記録一覧ビュー
class UR_UseListView(ListView):
    template_name = "app/usagerecord/use_list.html"
    model = UsageRecord
    context_object_name = "usagerecords"
    paginate_by = 10
    
    # 検索機能
    def get_queryset(self):
        search_date = self.request.GET.get('query_date')
        search_session = self.request.GET.get('query_session')

        if search_date and search_session:
            use_lists = UsageRecord.objects.filter(
                use_date = search_date, use_session = search_session)
        else:
            use_lists = UsageRecord.objects.all()
            # 降順に整列
            use_lists = UsageRecord.objects.order_by('-use_date')
            
        return use_lists

# 利用日登録ビュー
class UR_CreateView(CreateView):
    template_name = "app/usagerecord/create.html"
    model = UsageRecord
    # form_classの指定 (forms.pyでクラス定義)
    form_class = UsageRecordForm
    # 登録成功時に遷移する
    success_url = reverse_lazy("ur_use_list")
    
# 利用記録編集ビュー
class UR_UpdateView(UpdateView):
    template_name = "app/usagerecord/update.html"
    model = UsageRecord
    form_class = UsageRecordForm
    success_url = reverse_lazy("ur_use_list")

# 利用記録削除ビュー
class UR_DeleteView(DeleteView):
    template_name = "app/usagerecord/index.html"
    model = UsageRecord
    success_url = reverse_lazy("ur_use_list")

app/templates/app/base.html
<html lang="ja">
    <head>
        {% include "app/header.html" %}
    </head>

    <body>
        <!-- ここにコンテンツが表示される -->
        {% block content %}
        {% endblock %}

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    </body>
</html>

app/templates/app/header.html
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/list.css' %}">

<nav class="navbar navbar-expand-lg navbar-dark bg-info">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'index' %}">プール利用者管理</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarNav">
            <!--左寄せになる-->
            <ul class="navbar-nav me-auto">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'admin:index'%}">管理サイト</a>
                </li>

                <!--利用者情報に遷移-->
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'index'%}">利用者一覧</a>
                </li>

                <!--利用記録に遷移-->
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'ur_use_list'%}">利用記録</a>
                </li>
            </ul>
            <!--右寄せになる-->
            <ul class="navbar-nav ms-auto">
                <li class="nav-item">
                    <!--ログインしているならログアウトを表示-->
                    {% if user.is_authenticated %}
                        <a type="button" class="btn btn-danger" aria-current="page" data-bs-toggle="modal" data-bs-target="#logout-Modal" href="{% url 'logout' %}">ログアウト</a>
                        {% include 'registration/logout.html' %}

                    <!--していないならログインを表示-->
                    {% else %}
                        <a type="button" class="btn btn-success" class="nav-link active" aria-current="page" href="{% url 'login' %}">ログイン</a>
                    {% endif %}
                </li>
            </ul>
        </div>
    </div>
</nav>

app/templates/app/pagination.html
{% if is_paginated %}
    {% if page_obj.has_previous %}
        <a class="btn btn-outline-primary mb-4" href="?page=1">
            <svg xmlns="http://www.w3.org/2000/svg" width="14" height="24" fill="currentColor" class="bi bi-skip-start" viewBox="0 0 16 16">
                <path d="M4 4a.5.5 0 0 1 1 0v3.248l6.267-3.636c.52-.302 1.233.043 1.233.696v7.384c0 .653-.713.998-1.233.696L5 8.752V12a.5.5 0 0 1-1 0V4zm7.5.633L5.696 8l5.804 3.367V4.633z"/>
            </svg>
        </a>
        <a class="btn btn-outline-primary mb-4" href="?page={{page_obj.previous_page_number}}">
            <svg xmlns="http://www.w3.org/2000/svg" width="14" height="24" fill="currentColor" class="bi bi-caret-left" viewBox="0 0 16 16">
                <path d="M10 12.796V3.204L4.519 8 10 12.796zm-.659.753l-5.48-4.796a1 1 0 0 1 0-1.506l5.48-4.796A1 1 0 0 1 11 3.204v9.592a1 1 0 0 1-1.659.753z"/>
            </svg>
        </a>
    {% endif %}

    {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
        <a class="btn btn-primary mb-4" href="?page={{num}}">{{ num }}</a>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
        <a class="btn btn-outline-primary mb-4" href="?page={{num}}">{{ num }}</a>
        {% endif %}
    {% endfor %}

    {% if page_obj.has_next %}
        <a class="btn btn-outline-primary mb-4" href="?page={{page_obj.next_page_number}}">
            <svg xmlns="http://www.w3.org/2000/svg" width="14" height="24" fill="currentColor" class="bi bi-caret-right" viewBox="0 0 16 16">
                <path d="M6 12.796V3.204L11.481 8 6 12.796zm.659.753l5.48-4.796a1 1 0 0 0 0-1.506L6.66 2.451C6.011 1.885 5 2.345 5 3.204v9.592a1 1 0 0 0 1.659.753z"/>
            </svg>
        </a>
        <a class="btn btn-outline-primary mb-4" href="?page={{page_obj.paginator.num_pages}}">
            <svg xmlns="http://www.w3.org/2000/svg" width="14" height="24" fill="currentColor" class="bi bi-skip-end" viewBox="0 0 16 16">
                <path d="M12.5 4a.5.5 0 0 0-1 0v3.248L5.233 3.612C4.713 3.31 4 3.655 4 4.308v7.384c0 .653.713.998 1.233.696L11.5 8.752V12a.5.5 0 0 0 1 0V4zM5 4.633L10.804 8 5 11.367V4.633z"/>
            </svg>
        </a>
    {% endif %}
{% endif %}

app/templates/app/usagerecord/create.html
{% extends "app/base.html" %}

{% block content %}

<div clas="row">
    <div class="col-md-8 offset-md-2">
        <div class="mx-2 my-3">
            <h2>利用記録の登録</h2>
        </div>

        <div class="mx-2">
            <form method="POST" class="h-adr">
                {% csrf_token %}
                <!-- タグでフォームを生成 -->
                <table class="table table-striped " border="3">
                    <tr>
                        <th><label for="id_useroverview_fk">カード番号 No.</label></th>
                        <td>
                            <input type="text" name="useroverview_fk" pattern="^[0-9]+$" maxlength="8" required id="id_useroverview_fk">
                        </td>
                    </tr>
                    <tr>
                        <th><label for="id_use_session">利用時間帯</label></th>
                        <td>
                            <select name="use_session" id="id_use_session">
                                <option value="1" selected>午前の部</option>
                                <option value="2">午後の部</option>
                                <option value="3">夜の部</option>
                            </select>
                        </td>
                    </tr>
                </table>

                <br/>
                <button type="submit" class="btn btn-primary">登録</button>
                <button type="submit" class="btn btn-secondary" onclick="javascript:history.go(-1);" name="back" >戻る</button>

            </form>
        </div>
    </div>
</div>

{% endblock %}

app/templates/app/usagerecord/delete.html
<div class="modal fade" id="delete-Modal-{{ item.id }}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">利用記録の削除</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <p>削除すると元に戻せません。よろしいですか？
            </div>
            <div class="modal-footer">
                <form method='POST' action="{% url 'delete' item.id %}">
                {% csrf_token %}
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">キャンセル</button>
                    <button type="submit" class="btn btn-danger">削除</button>
                </form>
            </div>
        </div>
    </div>
</div>

app/templates/app/usagerecord/update.html
{% extends "app/base.html" %}

{% block content %}

<!--郵便番号-->
<script src="https://yubinbango.github.io/yubinbango/yubinbango.js" charset="UTF-8"></script>

<div clas="row">
    <div class="col-md-8 offset-md-2">
        <div class="mx-2 my-3">
            <h2>利用記録の更新・編集</h2>
        </div>

        <div class="mx-2">
            <form method="POST" class="h-adr">
                {% csrf_token %}
                <!-- タグでフォームを生成 -->
                <table class="table table-striped" border="3">
                    <tr>
                        <th><label for="id_useroverview_fk">カード番号 No.</label></th>
                        <td>
                            <input type="text" name="useroverview_fk" pattern="^[0-9]+$" maxlength="8" value="{{ object.useroverview_fk }}" required id="id_useroverview_fk">
                        </td>
                    </tr>
                    <tr>
                        <th><label for="id_use_date">利用日</label></th>
                        <td>
                            <input type="date" name="use_date" value="{{ object.use_date|date:'Y-m-d' }}" required id="id_use_date">
                        </td>
                    </tr>
                    <tr>
                        <th><label for="id_use_session">利用時間帯</label></th>
                        <td>
                            {{ form.use_session }}
                        </td>
                    </tr>
                </table>

                <br/>
                <button type="submit" class="btn btn-primary">更新</button>
                <button type="submit" class="btn btn-secondary" onclick="javascript:history.go(-1);" name="back" >戻る</button>

            </form>
        </div>
    </div>
</div>
{% endblock %}

app/templates/app/usagerecord/use_list.html
{% extends "app/base.html" %}

{% block content %}
<div class="container-fluid">
    <div clas="row">
        <div class="col-md-8 offset-md-2">
            <div class="mx-2 my-3">
                <h2>利用記録</h2>
            </div>

            <div class="d-md-flex flex-row">
                <div class="m-2">
                    <!--検索機能-->
                    <form action="" method="GET">
                        <input type="date" name="query_date" value="{{ request.GET.query_date }}" >

                        <select name="query_session" id="" value="{{ request.GET.query_session }}" >
                            <option value="">-------</option>
                            <option value="1">午前の部</option>
                            <option value="2">午後の部</option>
                            <option value="3">夜の部</option>
                        </select>

                        <button type="submit">検索する</button>
                    </form>
                </div>
            </div>

            <!-- データ表示 -->
            <div class="table-scroll">
                <table class="table table-striped" border="3">
                    <thead>
                        <th>利用日</th>
                        <th>利用時間帯</th>
                        <th>カード番号</th>
                        <th></th>
                        <th>                        
                            <a href="{% url 'ur_create' %}" class="btn btn-primary">新規登録</a>
                        </th>

                    </thead>
                    <tbody>
                        {% for item in usagerecords %}
                            <tr>
                                <!-- 利用日 -->
                                <td>{{ item.use_date }}</td>
                            
                                <!-- 利用時間帯 -->
                                <td>{{ item.get_use_session_display }}</td>

                                <!-- カード番号 -->
                                <td><a href="{% url 'detail' item.useroverview_fk %}">No. {{ item.useroverview_fk }}</a></td>

                                <!--編集-->
                                <td class="text-end">
                                    <a href="{% url 'ur_update' item.id %}" class="btn btn-success">編集</a>
                                </td>
                                <!--記録の削除-->
                                <td>
                                    <a type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#delete-Modal-{{ item.id }}">削除</a></td>
                                    {% include 'app/usagerecord/delete.html' %}
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<!--ページング機能-->
{% include 'app/pagination.html' %}

{% endblock %}

app/templates/app/useroverview/create.html
{% extends "app/base.html" %}

{% block content %}

<!-- 郵便番号 YubinBango -->
<script src="https://yubinbango.github.io/yubinbango/yubinbango.js" charset="UTF-8"></script>

<div clas="row">
    <div class="col-md-8 offset-md-2">
        <div class="mx-2 my-3">
            <h2>利用者の登録</h2>
        </div>

        <div class="mx-2">
            <form method="POST" class="h-adr">
                {% csrf_token %}
                <!-- タグでフォームを生成 -->
                <table class="table table-striped" border="3">
                    <tr>
                        <th><label for="id_name">氏名</label></th>
                        <td>
                            <input type="text" name="name" maxlength="200" required id="id_name">
                        </td>
                    </tr>
                    <tr>
                        <th><label for="id_birthday">生年月日</label></th>
                        <td>
                            <input type="date" name="birthday" required id="id_birthday">
                        </td>
                    </tr>
                    <tr>
                        <th><label for="id_gender">性別</label></th>
                        <td>
                            <select name="gender" id="id_gender">
                                <option value="1" selected>男性</option>
                                <option value="2">女性</option>
                                <option value="3">その他</option>
                            </select>
                        </td>
                    </tr>
                    <tr>
                        <th><label for="id_zip_code">郵便番号</label></th>
                        <td>
                            <span class="p-country-name" style="display:none;">Japan</span>
                            〒
                            <input type="text" name="zip_code1" class="p-postal-code" pattern="\d*" maxlength="3" size="3" required id="id_zip_code">
                            -
                            <input type="text" name="zip_code2" class="p-postal-code" pattern="\d*" maxlength="4" size="4" required id="id_zip_code">
                        </td>
                    </tr>
                    <tr>
                        <th><label for="id_address">住所</label></th>
                        <td>
                            <input type="text" name="address" class="p-region p-locality p-street-address p-extended-address" maxlength="200" required id="id_address" />
                        </td>
                    </tr>
                    <tr>
                        <th><label for="id_phone_number">電話番号</label></th>
                        <td>
                            <input type="text" name="phone_number" pattern="^[0-9]+$" maxlength="20" required id="id_phone_number">
                        </td>
                    </tr>
                    <tr>
                        <th><label for="id_temperature">体温</label></th>
                        <td>
                            <input type="number" name="temperature" min="30.0" max="43.0" step="0.1" required id="id_temperature">
                        </td>
                    </tr>
                </table>
                <br/>
                <button type="submit" class="btn btn-primary">登録</button>
                <button type="submit" class="btn btn-secondary" onclick="javascript:history.go(-1);" name="back" >戻る</button>
            </form>
        </div>
    </div>
</div>

{% endblock %}

app/templates/app/useroverview/delete.html
<div class="modal fade" id="delete-Modal-{{ item.id }}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">利用者の削除</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <p>削除すると元に戻せません。よろしいですか？
            </div>
            <div class="modal-footer">
                <form method='POST' action="{% url 'delete' item.id %}">
                    {% csrf_token %}
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">キャンセル</button>
                    <button type="submit" class="btn btn-danger">削除</button>
                </form>
            </div>
        </div>
    </div>
</div>

app/templates/app/useroverview/detail.html
{% extends "app/base.html" %}

{% block content %}

<div clas="row">
    <div class="col-md-8 offset-md-2">
        <div class="mx-2 my-3">
            <h2>利用者の詳細</h2>
        </div>

        <!-- 詳細なデータの表示-->
        <div class="mx-2">
            <table class="table" border="3">
                <tr>
                    <th><label for="id_id">カード番号</label></th>
                    <td>
                        No. {{ userdetailviews.id }}
                    </td>
                </tr>
                <tr>
                    <th><label for="id_name">氏名</label></th>
                    <td>
                        {{ userdetailviews.name }}
                    </td>
                </tr>
                <tr>
                    <th><label for="id_birthday">生年月日</label></th>
                    <td>
                        {{ userdetailviews.birthday }}
                    </td>
                </tr>
                <tr>
                    <th><label for="id_gender">性別</label></th>
                    <td>
                        {{ userdetailviews.get_gender_display }}
                    </td>
                </tr>
                <tr>
                    <th><label for="id_zip_code">郵便番号</label></th>
                    <td>
                        {{ userdetailviews.zip_code1 }}-{{ userdetailviews.zip_code2 }}
                    </td>
                </tr>
                <tr>
                    <th><label for="id_address">住所</label></th>
                    <td>
                        {{ userdetailviews.address }}
                    </td>
                </tr>
                <tr>
                    <th><label for="id_phone_number">電話番号</label></th>
                    <td>
                        {{ userdetailviews.phone_number }}
                    </td>
                </tr>
                <tr>
                    <th><label for="id_temperature">体温</label></th>
                    <td>
                        {{ userdetailviews.temperature }}
                    </td>
                </tr>
                <tr>
                    <th><label for="id_created_date">カード作成日</label></th>
                    <td>
                        {{ userdetailviews.created_date }}
                    </td>
                </tr>
            </table>

            <button type="submit" class="btn btn-secondary" onclick="javascript:history.go(-1);" name="back" >戻る</button>
        </div>
    </div>
</div>


{% endblock %}

app/templates/app/useroverview/update.html
{% extends "../base.html" %}

{% block content %}

<!--郵便番号-->
<script src="https://yubinbango.github.io/yubinbango/yubinbango.js" charset="UTF-8"></script>


<div clas="row">
    <div class="col-md-8 offset-md-2">
        <div class="mx-2 my-3">
            <h2>利用者の更新・編集</h2>
        </div>

        <div class="mx-2">
            <form method="POST" class="h-adr">
                {% csrf_token %}
                <!-- タグでフォームを生成 -->
                <table class="table table-striped" border="3">
                    <tr>
                        <th><label for="id_name">氏名</label></th>
                        <td>
                            {{ form.name }}
                        </td>
                    </tr>
                    <tr>
                        <th><label for="id_birthday">生年月日</label></th>
                        <td>
                            <input type="date" name="birthday" value="{{ object.birthday|date:'Y-m-d' }}" required id="id_birthday">
                        </td>
                    </tr>
                    <tr>
                        <th><label for="id_gender">性別</label></th>
                        <td>
                            {{ form.gender }}
                        </td>
                    </tr>
                    <tr>
                        <th><label for="id_zip_code">郵便番号</label></th>
                        <td>
                            <span class="p-country-name" style="display:none;">Japan</span>
                            〒
                            <input type="text" name="zip_code1" class="p-postal-code" value="{{ object.zip_code1 }}" pattern="^[0-9]+$" maxlength="3" size="3" required id="id_zip_code" inputmode="numeric">
                            -
                            <input type="text" name="zip_code2" class="p-postal-code" value="{{ object.zip_code2 }}" pattern="^[0-9]+$" maxlength="4" size="4" required id="id_zip_code" inputmode="numeric">
                        </td>
                    </tr>
                    <tr>
                        <th><label for="id_address">住所:</label></th>
                        <td>
                            <input type="text" name="address" class="p-region p-locality p-street-address p-extended-address" maxlength="200" required id="id_address" value="{{ object.address }}" />
                        </td>
                    </tr>
                    <tr>
                        <th><label for="id_phone_number">電話番号</label></th>
                        <td>
                            <input type="text" name="phone_number" pattern="^[0-9]+$" maxlength="20" required id="id_phone_number" value="{{ object.phone_number }}"  inputmode="numeric" />
                        </td>
                    </tr>
                    <tr>
                        <th><label for="id_temperature">体温</label></th>
                        <td>
                            {{ form.temperature }}
                        </td>
                    </tr>
                </table>

                <br/>
                <button type="submit" class="btn btn-primary">更新</button>
                <button type="submit" class="btn btn-secondary" onclick="javascript:history.go(-1);" name="back" >戻る</button>

            </form>
        </div>
    </div>
</div>

{% endblock %}